---
extends: "default"
rules:
  comments:
    min-spaces-from-content: 1
  empty-values: "enable"
  indentation:
    indent-sequences: "consistent"
  line-length: "disable"
  quoted-strings:
    quote-type: "double"
ignore: |
  .venv/
